trezor/trezor-user-env

.gitignore, controller/binaries.py, controller/main.py, controller/proxy.py, controller/shell.nix, firmware/bin/download.sh, init.sh
This is my branch, I continue on top of https://github.com/trezor/trezor-user-env/pull/32. It is a continued effort from https://github.com/trezor/trezor-suite/pull/2749.
My goal is to have it working under macOS. I'm also testing this in parallel under WSL2(ubuntu) on Windows 10. Learning Nix in the process.The utlimate goal is to have headless cyperss running both on macOS and Linux hosts.
The original code is pretty much broken for me on macOS and seems to be a bit outdated.
Issues encountered:
1. I had issues downloading firmwares, had a [small yak shaving excursion](https://github.com/trezor/trezor-firmware/pull/1333) into building them myself
2. Even if I had firmwares for correct platform on in proper folder, the python controller server wasn't picking them up - wrong working …
=> Darwin's branch

controller/index.html, controller/index.js
prevents reload while sending raw json message to user-env websocket server
=> fix: ui json form submit

controller/websocket_server.py
Allow requests with header "Connect: close" and respond with 200 OK
=> feat: websocket server health check request

.gitignore, Makefile, ci/prebuild.yml, setup.cfg, shell.nix
Including code checks into CI and making an easy `make check` command to check everything locally.
NOTE: in the #58 PR, there is a `tests` folder with mypy testing file, which should be then deleted, as this is much better approach.
=> feat(ci): code checks with mypy and flake8

.gitignore, docker/Dockerfile, docker/create_version_file.sh, run.sh, shell.nix
Trying to address issue #65
- when running a docker container, it shows multiple git details - the branch, commit amount (aka version) and the details of last commit
=> feat(docker): showing version details when running docker container

.gitignore, src/helpers.py
Preserving all the logs in a file, so that we can extract it from CI job and analyze in case of issues.
Connected with satoshilabs/devops#37
=> feat(logging): logging into debugging file in root folder

.gitignore, src/helpers.py
Separate folder for logs, so they can be easily extracted from the container in CI jobs
=> chore(logs): creating separate folder for logs

docs/SUMMARY.md, docs/controller.md
Addressing issue #84
- creating documentation for all controller's supported commands
=> feat(docs): supported commands for controller

README.md
Not for NixOS developers, but for NixOS users.
=> Small README improvements for NixOS users

README.md, ci/build.yml, ci/prebuild.yml, docker/bitcoin-regtest/Dockerfile, docker/bitcoin-regtest/entrypoint.sh, docker/bitcoin-regtest/start_regtest.sh, docker/compose.yml
This pr is the first step to introducing new functionality to tenv. This adds bitcoin core running in regtest mode and also our blocbook service that is connected to there. 
This is still a work in progress. Just putting it here so anyone interested can track the changes.
=> feat(ci): create bitcoid docker image and setup regtest mode

README.md
Documentation of how to run local Suite e2e tests against local trezor-user-env
=> chore(docs): steps how to debug locally against Suite e2e tests

docker/bitcoin-regtest/Dockerfile
Updates backend and blockbook. This resolves #111
=> chore(regtest): update blocbook and bitcoind binaries

README.md, ci/prebuild.yml, docker/Dockerfile, poetry.lock, pyproject.toml, run.sh, setup.cfg, shell.nix, src/emulator.py
As discussed in https://github.com/trezor/trezor-user-env/pull/124#issuecomment-991697879, adding support for `Poetry`, which enables us to immediately install new `python` packages
=> feat(python): introducing Poetry

src/emulator.py
Implements https://github.com/trezor/trezor-user-env/issues/125
- reusing already existing logic of `start`ing and `stop`ing emulator from `trezorlib`
=> chore(emulator): emulator start/stop taken from trezorlib._internal.emulator

src/emulator.py
looks like its working now (tested locally)
=> fix(emulator): enable experimental_features in emulator.apply_settings

.github/workflows/validation.yml
Adds validation checks (code check and style check) to GitHub actions in preparation for transition from Gitlab to GitHub actions for this project.
=> feat(ci): add validation checks to gh actions for pull requests

.github/workflows/build_and_push.yml, README.md, docker/Dockerfile, docker/compose.yml, run-nix.sh, run.sh, src/binaries.py, src/binaries/firmware/bin/download.sh, src/dashboard/index.html
- feat: add arm binary for bridge 2.0.31
- feat: setup for the arm64 image build
- feat(ci): add workflow for building and pushing images to gh registry
=> feat: introduce arm trezor-user-env and switch to GitHub actions 

run.sh
- Pulls git changes if on master branch (and `--no-pull` is not provided)
- Adds `--help`
- Opens `localhost:9002` in a web browser
- Some small refactor
=> Improve run.sh script

README.md
=> fix(docs): fix link to development.md

README.md, docker/compose.yml, run.sh
- fix: error on regtest start when recreating container `fixes` #156 
- fix: no video output device on linux `fixes` #118
=> tenv fixes when launching with docker

docker/bitcoin-regtest/Dockerfile
Updates bitcoind in regtest to version 23.0
=> chore: update regtest bitcoind to version 23.0

docker/Dockerfile, shell.nix
Updates nixos to upstream docker image.
=> chore(ci): update to the latest stable nix and official nix image

docker/Dockerfile, poetry.lock, pyproject.toml, shell.nix, src/binaries/firmware/bin/download.sh
Opening a PR so that the image is built and can be tried - connected with `Connect` issues
=> Nix-shell fix for patching

src/emulator.py
Fixing issue in Connect tests - `DeviceIsBusy` when doing some small tasks like `pressYes`.
The reason was that we connected to the whole `client` instead of just the `debuglink`.
=> fix(emu): differentiate between client and debuglink when connecting

.github/workflows/build_and_push_regtest.yml, docker/bitcoin-regtest/Dockerfile
add support for arm64 regtest with blockbook
=> feat: add regtest arm64 support

src/binaries.py
Adding support for new bridges. I could only test the `linux` bridge. @vdovhanych please try the `mac` one
=> feat(bridge): add new 2.0.32 bridges

src/controller.py
needed in suite tests https://github.com/trezor/trezor-suite/pull/7700
=> feat(regtest): add generate block

src/binaries/firmware/bin/download.sh
=> feat(emu): download the latest Model R build from master branch

docs/controller.md, src/binaries.py, src/binaries/firmware/bin/download.sh, src/controller.py, tests/controller_test.py
Naming changes from `master` to `main`
=> chore(binaries): change latest emulators name from master to main

.dockerignore, .gitignore, docker/Dockerfile, patch_emulators.sh, src/binaries.py, src/binaries/firmware/bin/download.sh
Reverts trezor/trezor-user-env#243
Sorry, I did not test it properly and it now causes issues for Suite team - the emulators are not there. My mistake
=> Revert "Fix/download emulators"

.editorconfig, src/binaries.py, src/binaries/firmware/bin/download_latest_gh.py, src/dashboard/index.html, src/dashboard/js/index.js, src/emulator.py
Adding dashboard functionality to load academic seed. 
Leaving the legacy all seed option.
Including unification of .editorconfig automatic formatting.
=> Loading academic seed

src/dashboard/index.html, src/dashboard/js/index.js
Fixes https://github.com/trezor/trezor-user-env/issues/256:
- makes the error notification more easily hide-able
Makes it possible to choose the passphrase_protection when loading the seed
=> Chore: small frontend improvements for Suite team

node_bridge/bin.js, shell.nix, src/binaries.py, src/bridge.py
Experimental support for node.js bridge --- just specify `"node"` as the bridge version
=> Nodejs bridge

src/binaries.py, src/controller.py
Hardcode the default bridge, so we do not get some future surprises when changing/adding new bridges
=> chore: set default bridge to 2.0.33

docs/controller.md, src/binaries.py, src/binaries/firmware/bin/download.sh, src/dashboard/js/index.js, src/emulator.py, tests/controller_test.py
Fixes https://github.com/trezor/trezor-user-env/issues/308:
- replace T2B1 with new T3B1
=> chore: rename all T2B1 mentions to T3B1, fetch only recent releases
