- controller/emulator.py
- controller/main.py
there was some refactoring to the scripts inside suite in the meantime. This PR backports this changes here. Suite will then switch to trezor-user-env
resolve #14
> chore: re-apply newer changes from suite scripts

- src/bridge.py
- src/bridge_proxy.py
Fixing problem in #72
- not raising RuntimeError when starting a component, even though it is already running - logging it and returning instead
> fix(controller): removing RuntimeErrors in start functions for bridge and proxy

- src/controller.py
- src/emulator.py
Addressing issue #54:
- `emulator-apply-settings` command takes all possible fields, so the emulator can be more precisely set up for testing purposes
- when it receives an unsupported field, client will be notified, as we relay all the fields, and an unknown field would cause an Exception
NOTE(s):
- the `homescreen` field is a bytes object, so client should send it decoded as string (to be sent in JSON), and we will encode it into bytes
- the `experimental_features` field is not supported yet, as it seems like the current `trezorlib` version 0.12.2 is not yet compatible with it
> feat(controller): emulator-apply-settings takes all possible fields

- src/controller.py
- src/dashboard/index.html
- src/dashboard/index.js
It is beneficial for testing purposes to start with empty device, for example when testing the onboarding process
> feat(index): checkbox for starting with wiped/empty device

- src/bridge.py
Addressing issue #86
- changing bridge status retrieving logic to just look whether the port is listening
> fix(bridge): bridge status based on whether port listens or not

- src/binaries.py
As mentioned in #91:
- putting the `master` version of emulator at the top of the dropdown select, to be immediately visible
> feat(index): current master-build of emulator goes first in dropdown

- docs/controller.md
- src/controller.py
- src/emulator.py
Enabling clients to click anywhere on the emulator, based on inputted coordinations
- addressing the issue with [one Suite test](https://github.com/trezor/trezor-suite/blob/e1c710e0c6bbd96b0e7970c15e3650c092aa0c83/packages/integration-tests/projects/suite-web/tests/onboarding/t2-recovery-success.test.ts#L12), where it is somehow impossible to click the `Continue` button in newer emulator versions (bigger than 2.1.4) at the end of successful backup
- (yes, it is kind of hack, we should troubleshoot properly why `pressYes` is not working there, but this `emulator-click` can be used elsewhere as well)
> feat(controller): command to click on specified emulator pixel coordination

- docker/bitcoin-regtest/entrypoint.sh
This PR addresses #102 
This seems to be the easiest solution to running the backend and filling it with bitcoins. As we need to wait a bit for the service to start, I had to add sleep, and in general, generating bitcoins will slow down the startup of the blockbook (approx 10-15 seconds) not sure if this could cause some problems with the tenv server @grdddj
> fix(ci): update regtest with default wallet and generate blocks

- docker/Dockerfile
This should fix launching the latest master version emulator. The problem was with different GCC lib versions and simple nix-channel update fixed that as we already were using unstable channel in the base docker image of tenv. 
fixes #116
> chore(nix): updating channel before we patch emulator files

- .gitignore
- docs/controller.md
- src/bridge.py
- src/controller.py
- src/dashboard/index.html
- src/dashboard/index.js
- src/emulator.py
- src/helpers.py
Connected with issues in https://github.com/trezor/trezor-firmware/pull/1972 with enormous log in `Gitlab` disabling us from seeing the final result of `Connect` tests and discussion with @matejcik 
Sending all the output from `emulator` and `bridge` into `logs/emulator_bridge.log`.
We could make this conditional on some parameter sent into `bridge.start()` and `emulator.start()` functions
> redirecting debug logs from emulator and bridge into a logfile

- src/dashboard/index.html
- src/dashboard/index.js
- src/emulator.py
Coming from discussion with @matejcik in https://github.com/trezor/trezor-firmware/pull/1972#issuecomment-987813473
When calling `allow_unsafe`, catching the possible error of not being able to apply it. The benefit is that any caller of `tenv` (like `connect` in our case) will not have to care about not calling it for lower versions not supporting safety checks.
Additionally we could check that the error message contains either `Unsupported safety-checks setting` (case for `T1`) or `No setting provided` (case for older `T2`). (Not to catch for example `Device is not initialized` when trying to allow checks on fresh device)
@matejcik from when does `T1` support safety checks (and does it really)? I am getting the errors even on `1.10.2`, which is relatively new
> chore(emulator): better handling of allow_unsafe

- ci/build.yml
Connected with #128 - just a quick change of marking the test build manual.
As discussed with @tsusanka, it would be nice for the job to accept a parameter, but is not really necessary at the moment.
Making it manual makes sense on its own to save quite a lot of `CI` time and resources
> feat(ci): making the test image build manual

- docs/controller.md
- src/binaries.py
- src/controller.py
- src/dashboard/index.html
- src/dashboard/index.js
- src/emulator.py
Connected with https://github.com/trezor/trezor-firmware/issues/1932 and https://github.com/trezor/trezor-user-env/issues/49
Ability to specify emulator URL which will be downloaded and run by `tenv`.
Tested using emulators from `Gitlab CI` - 
https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/1839236800/artifacts/raw/core/build/unix/trezor-emu-core
https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/1839236825/artifacts/raw/legacy/firmware/trezor.elf
> feat(emulator): allowing to download and run emulator from URL

- ci/build.yml
- ci/prebuild.yml
This will allow dev account to retry the job and will fix the error with permissions introduced in the new version.
> fix(ci): set direct group dependency proxy prefix

- ci/prebuild.yml
- docker/Dockerfile
This fixes the issue with the latest docker image that was deployed by the nix community. It moves away from the alpine image and uses native nixos as a base.
> chore(docker): pin to last working nix docker image

- .gitignore
- docs/controller.md
- src/controller.py
- src/emulator.py
Connected with https://github.com/trezor/trezor-user-env/issues/137
Allowing for clients to get the current screenshot of the device screen - encoded as a base64 string, so it can be transmitted through websocket in JSON format.
It is not the cleanest solution, as we need to save _all_ the screens, and when somebody requests current screenshot, we will return the latest one. That is because firmware currently does not have the functionality to save _just_ the current screen.
> feat(emulator): emulator-get-screenshot command to return base64 encoded screen

- docs/controller.md
- src/controller.py
- src/dashboard/index.html
- src/dashboard/index.js
- src/emulator.py
Improvement of https://github.com/trezor/trezor-user-env/pull/138
Creating optional argument to `emulator-start` (`save_screenshots`), defaulting to `False`, that should be switched to `True` when client want to use the new `emulator-get-screenshot` functionality.
Done like this because majority of clients will not use `emulator-get-screenshot`, and it would slow them down.
> feat(emulator): adding save_screenshots argument to emulator-start

- src/controller.py
- src/emulator.py
Does it look correct? I had trouble running trezor-user-env locally. Kept getting 'emulator process died" but I gues it was not connected to these changes. So this is not tested yet. will try again tomorrow.
> feat: pass strenght and backup_type to device.reset

- src/binaries.py
- src/dashboard/index.html
- src/dashboard/index.js
Connected with https://github.com/trezor/trezor-user-env/issues/147:
- making sure ARM machines will only show ARM emulators/bridges in `dashboard` and vice-versa
> feat(emu, bridge): only show relevant binaries - ARM vs nonARM

- docker/bitcoin-regtest/Dockerfile
changes the download link to data.trezor.io storage
> feat: change blockbook download source

- README.md
- docs/SUMMARY.md
- docs/development.md
This simplifies README, in particular:
- Moves the development section into its own "development.md" file.
- Removes duplicates.
> chore(docs): simplify README

- src/binaries.py
- src/bridge.py
- src/emulator.py
Connected with https://github.com/trezor/trezor-user-env/issues/159:
- even on `ARM`, allow request for "classic" emulator/bridge version, like `2.4.3` - and adding the `-arm`/`-arm64` suffix automatically if not there
> feat(emu, bridge): add ARM suffix if on ARM and suffix not there

- src/dashboard/index.html
- src/dashboard/index.js
Small changes connected with https://github.com/trezor/trezor-user-env/issues/157
Default dashboard after the change:
> chore(dashboard): delete Get screenshot button, reword Save screenshot checkbox

- .github/workflows/test.yml
- .gitlab-ci.yml
- Makefile
- ci/test.yml
- docs/controller.md
- poetry.lock
- pyproject.toml
- setup.cfg
- src/bridge.py
- src/bridge_proxy.py
- src/controller.py
- src/dashboard/index.html
- src/dashboard/index.js
- src/emulator.py
- tests/conftest.py
- tests/controller_test.py
Connected with https://github.com/trezor/trezor-user-env/issues/90 and https://github.com/trezor/trezor-user-env/issues/122
So far just some basic tests of `controller`, trying to call most of its commands and checking if we receive a response with `success: True` (or `success: False` in case of purposely failing commands)
The `controller` currently has to run on the background (be started manually)
Next steps/ideas:
- automatically spawn the `controller` before the tests and kill it after them
- include `pytest`
- include it into `CI`
- some advanced functions are omitted now, as they are relying on specific emulator state - `"emulator-read-and-confirm-mnemonic"` and `emulator-read-and-confirm-shamir-mnemonic`
- could include the `regtest` - but that would require spinning up the …
> chore(tests): basic tests for controller commands

- docs/controller.md
- src/controller.py
- tests/controller_test.py
Connected with https://github.com/trezor/trezor-user-env/issues/101:
- unifying `emulator-` prefixes for all emulator commands in controller
NOTE:
- it is a backwards-incompatible change, we agreed with @mroz22 that Suite tests will need to be changed after this
> chore(controller): rename select-num-of-words cmd to emulator-select-num-of-words

- shell.nix
This fixes an issue with procps not present for checking emulator status in the new image.
> fix: adding procps to nix-shell for checking emulator status by tenv

- docs/controller.md
- src/controller.py
- src/emulator.py
- tests/controller_test.py
Connected with https://github.com/trezor/trezor-user-env/issues/169:
- allowing to get at least some basic information about what is on the emulator screen
- new `emulator-get-debug-state` websocket command, which will return an object with sometimes useful data
Use-case:
- during `T1` recovery, it contains for example `"recovery_fake_word": "dish"` when there is a fake word, or `"recovery_word_pos": 18` when Trezor asks for a real word
- for `TT`, the most useful is probably `"layout_lines": ["RecoveryHomescreen", "Select number of words", ""]`, which tells what is currently displayed on the screen
CC @ondracja @mroz22 - this most probably solves your issue, please try with a testing image (should be downloadable soon from `ghcr.io/trezor/trezor-user-env:173`)
> feat(emu): add `emulator-get-debug-state` command

- .dockerignore
- docker/Dockerfile
- docker/compose.yml
- patch_emulators.sh
- poetry.lock
- pyproject.toml
- src/binaries.py
- src/binaries/firmware/bin/download.sh
- src/controller.py
- src/dashboard.py
- src/dashboard/index.css
- src/dashboard/index.html
- src/dashboard/index.js
- src/emulator.py
- src/helpers.py
- tests/controller_test.py
Connected with https://github.com/trezor/trezor-user-env/issues/176:
- supporting model R in `tenv`
Is a little hacky, for couple of reasons/limitations:
- we need the latest `trezorlib` for `model R` support, but it is unreleased
- I am unable to install it from our github repo through `poetry install` ([known issue](https://github.com/python-poetry/poetry/issues/755)), so I am doing it manually through `pip` in `Dockerfile` as a last step
- we need functional `model R` emulator(s), but they are not yet released
- in current `master` we do have it running, just with a very limited capabilities
- therefore, I am hardcoding download of from the "most featured branch" currently ([grdddj/trezor_r_passphrase_input](https://github.com/trezor/trezor-firmware/tree/grdddj/trezor_r_passphrase_input …
> Support model R emulators

- src/binaries/firmware/bin/download.sh
Quick fix solving https://github.com/trezor/trezor-user-env/issues/189:
- updating hardcoded URLs for the latest `model R` emulators - both `linux` and `mac`
> fix(bin): update URL for latest model R emulators

- src/binaries/firmware/bin/download.sh
Again changing the URL for model R.
This time, however, it should be lasting longer - I have increased the artifact expiry in firmware to be 10 weeks - [ec8dd58](https://github.com/trezor/trezor-firmware/pull/2277/commits/ec8dd5800b4b5589efaed2282a3ff2bb830c05f7)
Also creating error handling just in case we missed to update it again later
> chore: update URL for model R, create error handling for it

- docker/compose.yml
- run.sh
- src/bridge.py
- src/emulator.py
- src/helpers.py
- src/main.py
Making `tenv` compatible with a physical `Trezor`, so it can be used for some automated tasks/tests in debug mode.
The biggest difference is in the spawning of `bridge` - by default for emulators, it is run with `-u=false`, which disables listening on `USB`. For a physical device, we do not add any arguments to the `bridge`.
To avoid confusion for users, dashboard shows that `tenv` is expected to work with a physical device - in both the `bridge` and `emulator` sections:
(it does not actually check if the physical Trezor is connected, but we could add it)
Support for physical `Trezor` is enabled by `$PHYSICAL_TREZOR` env variable.
`run.sh` script has a new `-t` flag, that will set it inside the container.
> Support for physical Trezor

- docker/compose.yml
- src/controller.py
the use case for this: 
when a mac user wants to run cypress tests native this allows the cypress test to send commands to regtest container from a different container (tenv in this case) 
test (localhost) -> tenv (container) -> tenv to regtest on locahost (container 2) typically, this doesn't work, but when we use `http://host.docker.internal`, it should work.
> fix: test regtest controller over host.docker.internal

- src/controller.py
- src/dashboard/index.html
- src/dashboard/index.js
Connected with https://github.com/trezor/trezor-user-env/issues/106:
- creating a section in dashboard dedicated to `regtest` and allowing to interact with it
Allows for mining any number of blocks and for sending `rBTC` into a specified address.
> feat(dashboard): add regtest section to interact with backend

- poetry.lock
Fixing the issue with `Unsupported model` in case of Safe3
> chore(poetry): update trezorlib version to support Trezor Safe 3

- src/controller.py
So that it does not give errors when encountering mismatched storage from the different model
> chore(emu): wipe storage when changing the model

- README.md
- `./run.sh` will fail if docker is allowed in root mode only
> docs: add info about need for non-root docker

- docker/bitcoin-regtest/entrypoint.sh
With implementation of https://github.com/trezor/trezor-suite/issues/13160 and https://github.com/trezor/trezor-suite/issues/13159 it would be useful to make this config consistent with it.
> Enable mempoolfullrbf=1 for Regtest

- src/bridge_proxy.py
I think the bridge proxy has an issue with left over processes, so they should be killed the same way as in bridge.
It's not a critical issue, but gets rid of some errors such as this:
> fix: bridge proxy kill children as well

- src/binaries.py
Should fix Suite e2e tests, putting node-bridge at the last place in the list
> fix: make the nodejs bridge not-default

- docs/controller.md
- src/controller.py
- src/emulator.py
Fixed/added `read_and_confirm_mnemonic` for `T2T1` (12 words + Shamir) and `T3T1` (12, 20, 24 words one share)
Also added a new API method - `emulator-get-screen-content` ... getting a current screen title and text
> Read and confirm mnemonic - T2T1 and T3T1

- src/emulator.py
May fix https://github.com/trezor/trezor-suite/pull/14568:
- allow for `internal` device handling even when the `node` bridge is running - using `UDP` communication with the emulator, so it does not interfere with the running bridge
> fix: make all the commands work even with the new node bridge - use UDP

- src/bridge.py
- src/emulator.py
Is little bit awkward - using different communication for each bridge type - but should fix the issue in Suite CI
> fix: use UDP with node bridge, non-UDP with old bridge when communicating with emulator

- .github/workflows/check-validation.yml
- docker/Dockerfile-debian
resolve https://github.com/trezor/trezor-user-env/issues/269
fixup 1:
also turns out `--no-dev` is also [deprecated](https://github.com/trezor/trezor-user-env/actions/runs/11255274404/job/31294471939) :)
```
The `--no-dev` option is deprecated, use the `--only main` notation instead.
```
fixup 2:
it should be `--without dev` [docs](https://python-poetry.org/docs/cli/)
fixup 3:
turns out dev is required by  validation CI :)
> chore(ci): update poetry install params

- src/dashboard/js/index.js
- src/emulator.py
fixing problem 1:
`get_debug_state` tries to serialize non buffer fields/keys (1 indent missing)
edit: after further testing this change can be tricky. 
DebugLinkState may contain some other filed types not only bytes (like int for example) but in the same time they might be complex and not serializable.
see thp state:
<DebugLinkState: {'mnemonic_secret': b'all all all all all all all all all all all all', 'passphrase_protection': False, 'reset_entropy': b'', 'mnemonic_type': <BackupType.Bip39: 0>, 'tokens': ['{', '"component"', ': ', '"SimplePage"', ', ', '"active_page"', ': ', '0', ', ', '"page_count"', ': ', '2', ', ', '"content"', ': ', '{', '"component"', ': ', '"AddressDetails"', ', ', '"qr_code"', ': ', '{', '"component"', ': ', '"Frame"', ', ', '"title"', ': ', '{', '"component"', …
> fix: emulator.get_debug_state response

- docs/controller.md
- src/controller.py
- src/dashboard/index.html
- src/dashboard/js/index.js
- src/emulator.py
It is possible to specify firmware branch and we will try to find and start the specified emulator model from that branch.
Emulators are downloaded from `https://data.trezor.io/dev/firmware/emu-branches` dir - connected with https://github.com/trezor/trezor-firmware/pull/4358
NOTE: emulators for `arm` are not being built, so this feature is `Linux`-only ... but as CI is running on `Linux`, everybody can use it there (for automated `Suite` tests)
> feat: support starting emulator from a custom firmware branch

- src/helpers.py
So that it is easier to see when things are happening from looking at console/docker logs - for troubleshooting purposes
> chore: add datetime at the start of all prints into console

- src/controller.py
- src/dashboard/index.html
- src/dashboard/js/index.js
- src/emulator.py
Should help the strange timeouts in Suite tests
> Fix issues with new release emulators

- src/binaries/firmware/bin/download.sh
- src/binaries/firmware/bin/patch-bin.sh
i had it stashed for a while now and used it only locally
im running user-env natively on nixos and having some issues [since the configuration changed](https://github.com/trezor/trezor-user-env/commit/4cafe457980ce3d17f6c603dfde61a92e7ed6461)
1. dowloading binaries produces copies instead of override existing file. Wtih this fix it will skip dowloading
2. patching binaries does not work, the process doesnt throw any error but patched binary cannot be started
> fix: download and patch fw binaries on nixos

- src/binaries/firmware/bin/download.sh
Testing image with new emulators: ghcr.io/trezor/trezor-user-env:6553b975b5fc57193af9dd2c6b5df76c025528bf
> chore: add release 2.8.9 emulators

- src/controller.py
- src/dashboard/index.html
- src/dashboard/js/index.js
- src/emulator.py
Fixes https://github.com/trezor/trezor-user-env/issues/299:
- allows for running the emulator with animations turned on ... useful e.g. for making videos
> feat: allow for enabling emulator animations

- docker/Dockerfile-debian
- src/emulator.py
(hot) Fixes https://github.com/trezor/trezor-user-env/issues/316 ... instead of installing `trezorlib` from the `main` firmware branch, using a specific commit hash "pre-thp-changes"
Fixes https://github.com/trezor/trezor-user-env/issues/314 ... for some reason the `ps -ef` command started being truncated, which caused the emulator status not being correctly seen
> Pin old trezorlib commit && Fix the emulator status

- docker/Dockerfile-debian
before this, I kept getting this locally
```
websocket_error_message: TrezorFailure - TrezorFailure(<FailureType.DataError: 3>, 'Failed to decode message: Missing required field. app_name', <Failure: {'code': <FailureType.DataError: 3>, 'message': 'Failed to decode message: Missing required field. app_name'}>)
```
> Update trezor lib
